### ISSUE TITLE
Add JS Docs comments

### ISSUE THREAD

**Issue by gregthompson27** [SpecTrail5/I-dont-Know#1]
https://github.com/SpecTrail5/I-dont-Know/blob/aaa4da38f456607dabc7355d39dfaf7fd9c50a07/index.js#L5-L11

@SpecTrail5, let's get some [JS Doc-style comments](https://jsdoc.app/tags-param.html) added for this calculate distance function.

**Comment by SpecTrail5** [comment]
Got it.
